# ----------------------------------------------------------------
# Based on: https://github.com/greghendershott/travis-racket
# ----------------------------------------------------------------
language: c

os: linux

dist: trusty
sudo: enabled

env:
  global:
    - RACKET_DIR=~/racket

  matrix:
    - RACKET_VERSION=6.7

install:
- git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
- cat ~/travis-racket/install-racket.sh | bash # pipe to bash not sh!
- export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

script:
 - raco test src
